# Non-secret configuration for prod environment
stack_name: cloud-resume-challenge-prod
bucket_name: borisatudn.online # Will need a different name for dev deployment since bucket names must be unique
region: us-east-1
