stack_name: "cloud-resume-challenge-{{ env }}"
bucket_name: "exampro-cloud-resume-certification-{{ env }}"
region: us-east-1
custom_domain: borisatudn.online # Will need something different for prod/dev/qa
