stack_name: "cloud-resume-challenge-{{ env }}"
bucket_name: "exampro-cloud-resume-certification-{{ env }}"
region: us-east-1 # Should not be changed - cloudfront requirement
custom_domain: "{% if env == 'prod' %}borisatudn.online{% endif %}"
hosted_zone_id: "{% if env == 'prod' %}Z03288392WB9D6DZ87EIB{% endif %}"
