$ANSIBLE_VAULT;1.1;AES256
34656335356432313263663538396430616464646437623939393062393663366666336235303166
6166666239353562663133323265663164333739356138320a393937663161383332313532633563
35323263303865356566346534633766363731613862653565666333303262633538356132633137
3532613135373961370a313337613735323636343038623564616263323332313636363833373361
36373830663864613337313134656639616237343635616261323939363836313035643063336336
66623534646530636261636166383031373562653961613763663562396265396234623036383731
38666636323330353238623935383634646437326662373038393761373366366436323736343030
37666432663530663633363630353935316361313563383033393737343434616235653734373662
36626136626132316639663534386263376335633938316236626335613261306135393564633664
35613134376238623464373634633535633565373763623465306336333666383765366637333633
303130666462633635346439343934313464
