frontend_stack_name: "cloud-resume-challenge-frontend-{{ env }}"
bucket_name: "exampro-cloud-resume-certification-{{ env }}"
region: us-east-1 # Should not be changed - cloudfront requirement
custom_domain: "{{ 'borisatudn.online' if env == 'prod' else '' }}"
hosted_zone_id: "{{ 'Z03288392WB9D6DZ87EIB' if env == 'prod' else '' }}"
