frontend_stack_name: "cloud-resume-challenge-frontend-{{ env }}"
bucket_name: "cloud-resume-webpage-{{ env }}"
custom_ddomain_name: "{% if env == 'prod' %}borisatudn.online{% else %}{{ env }}.borisatudn.online{% endif %}"
