name: CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  deploy-prod:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    environment: production
    env:
      ENV: ${{ vars.ENV }}
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: production
    secrets: inherit

  deploy-qa:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: quality-assurance
    env:
      ENV: ${{ vars.ENV }}
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: quality-assurance
    secrets: inherit

  deploy-dev:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    environment: development
    env:
      ENV: ${{ vars.ENV }}
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: development
    secrets: inherit
