name: CD Pipeline

jobs:
  deploy-prod:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: production
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

  deploy-qa:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: quality-assurance
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

  deploy-dev:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: development
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}